pipeline {
    agent any

    environment{
        DOCKER_ACCESS_TOKEN = credentials('docker-pat')
        IMAGE_TAG="${BUILD_NUMBER}"
    }

    stages{
        stage('checkout'){
            steps{
                git credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670',branch: 'main', url : "https://github.com/kriteshsharma/Makerble.git"
            }
        }
        stage('Build Image '){
            steps{
                    sh '''
                    echo 'Building docker image'
                    docker build -t krsharma/makerble:${BUILD_NUMBER} Application/.
                    echo 'Image built successfully'
                    '''
            }
        }
        stage('Push Image '){
            steps {
                script {
                    echo 'Logging in to Docker Hub with access token'
            withCredentials([string(credentialsId: 'docker-pat', variable: 'DOCKER_ACCESS_TOKEN')]) {
                sh "echo $DOCKER_ACCESS_TOKEN | docker login -u _json_key --password-stdin registry.hub.docker.com"
                echo 'Pushing docker image'
                docker.withRegistry('https://registry.hub.docker.com', 'docker-pat') {
                    docker.image("krsharma/makerble:${BUILD_NUMBER}").push()
                }
                echo 'Image pushed successfully'
                    }
                }
            }
        }
        stage('Update manifest file'){
            environment{
                 GIT_REPO_NAME = "Makerble"
                GIT_USER_NAME = "kriteshsharma"
            }
            steps{
                script{
                    withCredentials([string(credentialsId: 'git-token', variable: 'GITHUB_TOKEN')]) {
                        def BUILD_NUMBER = env.BUILD_NUMBER
                        def currentImageTag = sh(script: "cat manifest/rails-deployment.yaml | grep 'image: krsharma/makerble:' | sed 's/.*://' | tr -d ' '", returnStdout: true).trim()
                        // Calculate the new image tag by incrementing the current tag
                        if (currentImageTag && currentImageTag.isNumber()) {
                            // Calculate the new image tag by incrementing the current tag
                            echo "Current Image Tag: ${currentImageTag}"
                            echo "New Image Tag: ${BUILD_NUMBER}"
                            // Use sed to replace the image tag in the deployment file
                            sh """
                                sed -i 's|krsharma/makerble:${currentImageTag}|krsharma/makerble:${BUILD_NUMBER}|g' manifest/rails-deployment.yaml
                                cat manifest/rails-deployment.yaml
                                git config user.name "Kritesh Sharma"
                                git config user.email "kritesh.bhojnagar@gmail.com"
                                git add manifest/rails-deployment.yaml
                                git commit -m "updated manifest file using jenkins ci"
                                git remote -v
                                git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main  
                            """
                            } 
                        else {
                            error "Failed to extract or process the image tag."
                        }
                    }
                }
            }
        }
    }
}
