pipeline {
    agent any

    environment{
        DOCKERHUB_CREDENTIALS_PSW=credentials('docker-pass')
        IMAGE_TAG="${BUILD_NUMBER}"
    }

    stages{
        stage('checkout'){
            steps{
                git credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670',branch: 'main', url : "https://github.com/kriteshsharma/Makerble.git"
            }
        }
        stage('Build Image '){
            steps{
                    sh '''
                    echo 'Building docker image'
                    docker build -t krsharma/makerble:${BUILD_NUMBER} Application/.
                    echo 'Image built successfully'
                    '''
            }
        }
        stage('login') {
            steps{
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u krsharma --password-stdin'
            }
        }
        stage('Push Image '){
            steps{
                sh '''
                echo 'Pushing docker image'
                docker push krsharma/python-ci-cd:${BUILD_NUMBER} 
                '''
            }
        }
        stage('Update manifest file'){
            environment{
                 GIT_REPO_NAME = "Makerble"
                GIT_USER_NAME = "kriteshsharma"
            }
            steps{
                script{
                    withCredentials([string(credentialsId: 'git-token', variable: 'GITHUB_TOKEN')]) {
                        def BUILD_NUMBER = env.BUILD_NUMBER
                        def currentImageTag = sh(script: "cat manifest/rails-deployment.yaml | grep 'image: krsharma/makerble:' | sed 's/.*://' | tr -d ' '", returnStdout: true).trim()
                        // Calculate the new image tag by incrementing the current tag
                        if (currentImageTag && currentImageTag.isNumber()) {
                            // Calculate the new image tag by incrementing the current tag
                            echo "Current Image Tag: ${currentImageTag}"
                            echo "New Image Tag: ${BUILD_NUMBER}"
                            // Use sed to replace the image tag in the deployment file
                            sh """
                                sed -i 's|krsharma/makerble:${currentImageTag}|krsharma/makerble:${BUILD_NUMBER}|g' manifest/rails-deployment.yaml
                                cat manifest/rails-deployment.yaml
                                git config user.name "Kritesh Sharma"
                                git config user.email "kritesh.bhojnagar@gmail.com"
                                git add manifest/rails-deployment.yaml
                                git commit -m "updated manifest file using jenkins ci"
                                git remote -v
                                git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main  
                            """
                            } 
                        else {
                            error "Failed to extract or process the image tag."
                        }
                    }
                }
            }
        }
    }
}
