apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-web
  template:
    metadata:
      labels:
        app: demo-web
    spec:
      containers:
        - name: demo-web
          image: krsharma/makerble:1
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: myapp-config
          volumeMounts:
            - name: app-storage
              mountPath: /rails/storage
      volumes:
        - name: app-storage
          emptyDir: {}
